Updated docs of repo
alippo-com/GrowthBook-SDK-Flutter pull request #4
Opened 2022-04-16 06:11 UTC by DK070202

- Added detailed docs of repo.

2022-04-16 08:22 UTC, princebansal requested changes

2022-04-16 22:29 UTC, Auz commented on README.md
> +# Growth Book - SDK
1. GrowthBook has no space. (this is through out this document)
2. Removing the flutter from the name - is that on purpose? Just wondering if people will know what it's for or how it is different than the other SDKs.

2022-04-16 22:29 UTC, Auz commented on README.md
> +1. Create a Growth Book API key
1. Create a GrowthBook API key from the GrowthBook App

2022-04-16 22:29 UTC, Auz commented on README.md
> +
Maybe add a brief overview here? Perhaps something like:

GrowthBook is an open source feature flagging and experimentation platform that makes it easy to adjust what features are shown users, and run A/B tests, without deploying new code. There are two parts to GrowthBook, the GrowthBook Application, and the SDKs which implement this functionality to your code base. This Flutter SDK allows you to use GrowthBook with your Flutter based mobile application.

2022-04-30 16:56 UTC, Auz commented on README.md
> +2. At the start of your app,  do SDK Initialization as per below
Minor text edit: 
Initialize the SDK within your app using the API key, as below. 
or 
Initialize the SDK at the start of your app using the API key, as below.

2022-04-30 17:51 UTC, merged